//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Medicons.DigitalSignatures {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class SignServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class wsClientTransactionLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionTypeField;
        
        private string fileNameField;
        
        private string fileSizeField;
        
        private string processExceptionField;
        
        private string processStatusField;
        
        private string remoteIPField;
        
        private string requestIdField;
        
        private long requestTimeField;
        
        private bool requestTimeFieldSpecified;
        
        private string workerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
                this.RaisePropertyChanged("actionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string processException {
            get {
                return this.processExceptionField;
            }
            set {
                this.processExceptionField = value;
                this.RaisePropertyChanged("processException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string processStatus {
            get {
                return this.processStatusField;
            }
            set {
                this.processStatusField = value;
                this.RaisePropertyChanged("processStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string remoteIP {
            get {
                return this.remoteIPField;
            }
            set {
                this.remoteIPField = value;
                this.RaisePropertyChanged("remoteIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
                this.RaisePropertyChanged("requestTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestTimeSpecified {
            get {
                return this.requestTimeFieldSpecified;
            }
            set {
                this.requestTimeFieldSpecified = value;
                this.RaisePropertyChanged("requestTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string workerName {
            get {
                return this.workerNameField;
            }
            set {
                this.workerNameField = value;
                this.RaisePropertyChanged("workerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class wsClientTransactionLogs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private wsClientTransactionLog[] itemsField;
        
        private int pageCountField;
        
        private int pageNumberField;
        
        private long totalItemCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public wsClientTransactionLog[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("pageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long totalItemCount {
            get {
                return this.totalItemCountField;
            }
            set {
                this.totalItemCountField = value;
                this.RaisePropertyChanged("totalItemCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class RequestFailedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class InternalServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class ClientNotAuthorizeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://clientws.signserver.org/", ConfigurationName="DigitalSignatures.ClientWS")]
    public interface ClientWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.SignServerException), Action="", Name="SignServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse queryClientTransactionLogbyEmailOrPhone(CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse> queryClientTransactionLogbyEmailOrPhoneAsync(CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.RequestFailedException), Action="", Name="RequestFailedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.ClientNotAuthorizeException), Action="", Name="ClientNotAuthorizeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.validateDataResponse validateData(CMS_Medicons.DigitalSignatures.validateData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateDataResponse> validateDataAsync(CMS_Medicons.DigitalSignatures.validateData request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.validateOTPResponse validateOTP(CMS_Medicons.DigitalSignatures.validateOTP request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateOTPResponse> validateOTPAsync(CMS_Medicons.DigitalSignatures.validateOTP request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.generateOTPResponse generateOTP(CMS_Medicons.DigitalSignatures.generateOTP request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.generateOTPResponse> generateOTPAsync(CMS_Medicons.DigitalSignatures.generateOTP request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.RequestFailedException), Action="", Name="RequestFailedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.processSODResponse processSOD(CMS_Medicons.DigitalSignatures.processSOD request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processSODResponse> processSODAsync(CMS_Medicons.DigitalSignatures.processSOD request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.RequestFailedException), Action="", Name="RequestFailedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.InternalServerException), Action="", Name="InternalServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CMS_Medicons.DigitalSignatures.ClientNotAuthorizeException), Action="", Name="ClientNotAuthorizeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.processDataResponse processData(CMS_Medicons.DigitalSignatures.processData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processDataResponse> processDataAsync(CMS_Medicons.DigitalSignatures.processData request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CMS_Medicons.DigitalSignatures.customerLoginResponse customerLogin(CMS_Medicons.DigitalSignatures.customerLogin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.customerLoginResponse> customerLoginAsync(CMS_Medicons.DigitalSignatures.customerLogin request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryClientTransactionLogbyEmailOrPhone", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class queryClientTransactionLogbyEmailOrPhone {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailOrPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize;
        
        public queryClientTransactionLogbyEmailOrPhone() {
        }
        
        public queryClientTransactionLogbyEmailOrPhone(string emailOrPhone, int pageNumber, int pageSize) {
            this.emailOrPhone = emailOrPhone;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryClientTransactionLogbyEmailOrPhoneResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class queryClientTransactionLogbyEmailOrPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.wsClientTransactionLogs @return;
        
        public queryClientTransactionLogbyEmailOrPhoneResponse() {
        }
        
        public queryClientTransactionLogbyEmailOrPhoneResponse(CMS_Medicons.DigitalSignatures.wsClientTransactionLogs @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class metadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateData", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class validateData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.metadata[] metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data;
        
        public validateData() {
        }
        
        public validateData(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            this.worker = worker;
            this.metadata = metadata;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDataResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class validateDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public validateDataResponse() {
        }
        
        public validateDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class otpResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        private string otpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string otp {
            get {
                return this.otpField;
            }
            set {
                this.otpField = value;
                this.RaisePropertyChanged("otp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateOTP", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class validateOTP {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otp;
        
        public validateOTP() {
        }
        
        public validateOTP(string phoneNumber, string otp) {
            this.phoneNumber = phoneNumber;
            this.otp = otp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateOTPResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class validateOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.otpResponse @return;
        
        public validateOTPResponse() {
        }
        
        public validateOTPResponse(CMS_Medicons.DigitalSignatures.otpResponse @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class otpRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apiPassField;
        
        private string apiUserField;
        
        private string contractIdField;
        
        private string enpointField;
        
        private string labelIdField;
        
        private string messageField;
        
        private string phoneNumberField;
        
        private string templateIdField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apiPass {
            get {
                return this.apiPassField;
            }
            set {
                this.apiPassField = value;
                this.RaisePropertyChanged("apiPass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apiUser {
            get {
                return this.apiUserField;
            }
            set {
                this.apiUserField = value;
                this.RaisePropertyChanged("apiUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contractId {
            get {
                return this.contractIdField;
            }
            set {
                this.contractIdField = value;
                this.RaisePropertyChanged("contractId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string enpoint {
            get {
                return this.enpointField;
            }
            set {
                this.enpointField = value;
                this.RaisePropertyChanged("enpoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string labelId {
            get {
                return this.labelIdField;
            }
            set {
                this.labelIdField = value;
                this.RaisePropertyChanged("labelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
                this.RaisePropertyChanged("templateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateOTP", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class generateOTP {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.otpRequest otpReq;
        
        public generateOTP() {
        }
        
        public generateOTP(CMS_Medicons.DigitalSignatures.otpRequest otpReq) {
            this.otpReq = otpReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateOTPResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class generateOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.otpResponse @return;
        
        public generateOTPResponse() {
        }
        
        public generateOTPResponse(CMS_Medicons.DigitalSignatures.otpResponse @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class sodRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataGroup[] dataGroupField;
        
        private string ldsVersionField;
        
        private string unicodeVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataGroup[] dataGroup {
            get {
                return this.dataGroupField;
            }
            set {
                this.dataGroupField = value;
                this.RaisePropertyChanged("dataGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ldsVersion {
            get {
                return this.ldsVersionField;
            }
            set {
                this.ldsVersionField = value;
                this.RaisePropertyChanged("ldsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string unicodeVersion {
            get {
                return this.unicodeVersionField;
            }
            set {
                this.unicodeVersionField = value;
                this.RaisePropertyChanged("unicodeVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class dataGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class sodResponse : dataResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sodResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class dataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string archiveIdField;
        
        private byte[] dataField;
        
        private metadata[] metadataField;
        
        private int requestIdField;
        
        private byte[] signerCertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string archiveId {
            get {
                return this.archiveIdField;
            }
            set {
                this.archiveIdField = value;
                this.RaisePropertyChanged("archiveId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] signerCertificate {
            get {
                return this.signerCertificateField;
            }
            set {
                this.signerCertificateField = value;
                this.RaisePropertyChanged("signerCertificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processSOD", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class processSOD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.metadata[] metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.sodRequest sodData;
        
        public processSOD() {
        }
        
        public processSOD(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, CMS_Medicons.DigitalSignatures.sodRequest sodData) {
            this.worker = worker;
            this.metadata = metadata;
            this.sodData = sodData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processSODResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class processSODResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.sodResponse @return;
        
        public processSODResponse() {
        }
        
        public processSODResponse(CMS_Medicons.DigitalSignatures.sodResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processData", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class processData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.metadata[] metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data;
        
        public processData() {
        }
        
        public processData(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            this.worker = worker;
            this.metadata = metadata;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processDataResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class processDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.dataResponse @return;
        
        public processDataResponse() {
        }
        
        public processDataResponse(CMS_Medicons.DigitalSignatures.dataResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerLogin", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class customerLogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailOrPhone;
        
        public customerLogin() {
        }
        
        public customerLogin(string emailOrPhone) {
            this.emailOrPhone = emailOrPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerLoginResponse", WrapperNamespace="http://clientws.signserver.org/", IsWrapped=true)]
    public partial class customerLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://clientws.signserver.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CMS_Medicons.DigitalSignatures.otpResponse @return;
        
        public customerLoginResponse() {
        }
        
        public customerLoginResponse(CMS_Medicons.DigitalSignatures.otpResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientWSChannel : CMS_Medicons.DigitalSignatures.ClientWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientWSClient : System.ServiceModel.ClientBase<CMS_Medicons.DigitalSignatures.ClientWS>, CMS_Medicons.DigitalSignatures.ClientWS {
        
        public ClientWSClient() {
        }
        
        public ClientWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse CMS_Medicons.DigitalSignatures.ClientWS.queryClientTransactionLogbyEmailOrPhone(CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone request) {
            return base.Channel.queryClientTransactionLogbyEmailOrPhone(request);
        }
        
        public CMS_Medicons.DigitalSignatures.wsClientTransactionLogs queryClientTransactionLogbyEmailOrPhone(string emailOrPhone, int pageNumber, int pageSize) {
            CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone inValue = new CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone();
            inValue.emailOrPhone = emailOrPhone;
            inValue.pageNumber = pageNumber;
            inValue.pageSize = pageSize;
            CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).queryClientTransactionLogbyEmailOrPhone(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse> CMS_Medicons.DigitalSignatures.ClientWS.queryClientTransactionLogbyEmailOrPhoneAsync(CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone request) {
            return base.Channel.queryClientTransactionLogbyEmailOrPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhoneResponse> queryClientTransactionLogbyEmailOrPhoneAsync(string emailOrPhone, int pageNumber, int pageSize) {
            CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone inValue = new CMS_Medicons.DigitalSignatures.queryClientTransactionLogbyEmailOrPhone();
            inValue.emailOrPhone = emailOrPhone;
            inValue.pageNumber = pageNumber;
            inValue.pageSize = pageSize;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).queryClientTransactionLogbyEmailOrPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.validateDataResponse CMS_Medicons.DigitalSignatures.ClientWS.validateData(CMS_Medicons.DigitalSignatures.validateData request) {
            return base.Channel.validateData(request);
        }
        
        public string validateData(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            CMS_Medicons.DigitalSignatures.validateData inValue = new CMS_Medicons.DigitalSignatures.validateData();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.data = data;
            CMS_Medicons.DigitalSignatures.validateDataResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).validateData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateDataResponse> CMS_Medicons.DigitalSignatures.ClientWS.validateDataAsync(CMS_Medicons.DigitalSignatures.validateData request) {
            return base.Channel.validateDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateDataResponse> validateDataAsync(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            CMS_Medicons.DigitalSignatures.validateData inValue = new CMS_Medicons.DigitalSignatures.validateData();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.data = data;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).validateDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.validateOTPResponse CMS_Medicons.DigitalSignatures.ClientWS.validateOTP(CMS_Medicons.DigitalSignatures.validateOTP request) {
            return base.Channel.validateOTP(request);
        }
        
        public CMS_Medicons.DigitalSignatures.otpResponse validateOTP(string phoneNumber, string otp) {
            CMS_Medicons.DigitalSignatures.validateOTP inValue = new CMS_Medicons.DigitalSignatures.validateOTP();
            inValue.phoneNumber = phoneNumber;
            inValue.otp = otp;
            CMS_Medicons.DigitalSignatures.validateOTPResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).validateOTP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateOTPResponse> CMS_Medicons.DigitalSignatures.ClientWS.validateOTPAsync(CMS_Medicons.DigitalSignatures.validateOTP request) {
            return base.Channel.validateOTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.validateOTPResponse> validateOTPAsync(string phoneNumber, string otp) {
            CMS_Medicons.DigitalSignatures.validateOTP inValue = new CMS_Medicons.DigitalSignatures.validateOTP();
            inValue.phoneNumber = phoneNumber;
            inValue.otp = otp;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).validateOTPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.generateOTPResponse CMS_Medicons.DigitalSignatures.ClientWS.generateOTP(CMS_Medicons.DigitalSignatures.generateOTP request) {
            return base.Channel.generateOTP(request);
        }
        
        public CMS_Medicons.DigitalSignatures.otpResponse generateOTP(CMS_Medicons.DigitalSignatures.otpRequest otpReq) {
            CMS_Medicons.DigitalSignatures.generateOTP inValue = new CMS_Medicons.DigitalSignatures.generateOTP();
            inValue.otpReq = otpReq;
            CMS_Medicons.DigitalSignatures.generateOTPResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).generateOTP(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.generateOTPResponse> CMS_Medicons.DigitalSignatures.ClientWS.generateOTPAsync(CMS_Medicons.DigitalSignatures.generateOTP request) {
            return base.Channel.generateOTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.generateOTPResponse> generateOTPAsync(CMS_Medicons.DigitalSignatures.otpRequest otpReq) {
            CMS_Medicons.DigitalSignatures.generateOTP inValue = new CMS_Medicons.DigitalSignatures.generateOTP();
            inValue.otpReq = otpReq;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).generateOTPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.processSODResponse CMS_Medicons.DigitalSignatures.ClientWS.processSOD(CMS_Medicons.DigitalSignatures.processSOD request) {
            return base.Channel.processSOD(request);
        }
        
        public CMS_Medicons.DigitalSignatures.sodResponse processSOD(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, CMS_Medicons.DigitalSignatures.sodRequest sodData) {
            CMS_Medicons.DigitalSignatures.processSOD inValue = new CMS_Medicons.DigitalSignatures.processSOD();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.sodData = sodData;
            CMS_Medicons.DigitalSignatures.processSODResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).processSOD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processSODResponse> CMS_Medicons.DigitalSignatures.ClientWS.processSODAsync(CMS_Medicons.DigitalSignatures.processSOD request) {
            return base.Channel.processSODAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processSODResponse> processSODAsync(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, CMS_Medicons.DigitalSignatures.sodRequest sodData) {
            CMS_Medicons.DigitalSignatures.processSOD inValue = new CMS_Medicons.DigitalSignatures.processSOD();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.sodData = sodData;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).processSODAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.processDataResponse CMS_Medicons.DigitalSignatures.ClientWS.processData(CMS_Medicons.DigitalSignatures.processData request) {
            return base.Channel.processData(request);
        }
        
        public CMS_Medicons.DigitalSignatures.dataResponse processData(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            CMS_Medicons.DigitalSignatures.processData inValue = new CMS_Medicons.DigitalSignatures.processData();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.data = data;
            CMS_Medicons.DigitalSignatures.processDataResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).processData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processDataResponse> CMS_Medicons.DigitalSignatures.ClientWS.processDataAsync(CMS_Medicons.DigitalSignatures.processData request) {
            return base.Channel.processDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.processDataResponse> processDataAsync(string worker, CMS_Medicons.DigitalSignatures.metadata[] metadata, byte[] data) {
            CMS_Medicons.DigitalSignatures.processData inValue = new CMS_Medicons.DigitalSignatures.processData();
            inValue.worker = worker;
            inValue.metadata = metadata;
            inValue.data = data;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).processDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CMS_Medicons.DigitalSignatures.customerLoginResponse CMS_Medicons.DigitalSignatures.ClientWS.customerLogin(CMS_Medicons.DigitalSignatures.customerLogin request) {
            return base.Channel.customerLogin(request);
        }
        
        public CMS_Medicons.DigitalSignatures.otpResponse customerLogin(string emailOrPhone) {
            CMS_Medicons.DigitalSignatures.customerLogin inValue = new CMS_Medicons.DigitalSignatures.customerLogin();
            inValue.emailOrPhone = emailOrPhone;
            CMS_Medicons.DigitalSignatures.customerLoginResponse retVal = ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).customerLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.customerLoginResponse> CMS_Medicons.DigitalSignatures.ClientWS.customerLoginAsync(CMS_Medicons.DigitalSignatures.customerLogin request) {
            return base.Channel.customerLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CMS_Medicons.DigitalSignatures.customerLoginResponse> customerLoginAsync(string emailOrPhone) {
            CMS_Medicons.DigitalSignatures.customerLogin inValue = new CMS_Medicons.DigitalSignatures.customerLogin();
            inValue.emailOrPhone = emailOrPhone;
            return ((CMS_Medicons.DigitalSignatures.ClientWS)(this)).customerLoginAsync(inValue);
        }
    }
}
